# -*- coding: utf-8 -*-
"""Test_6months_stock_news

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXXkhWD0gHwjswb0C5IGGkFUnvyMKW9D
"""

!pip install alpaca-trade-api nltk pandas requests

"""1. I tried VADER first ⬇️

Time span: **2026 January**

"""

# Extract the news in Jan.2026

import pandas as pd
import requests
import time

# 1. API Configuration
API_KEY = "PKVESCM6H235I3XWBT25AYP7JC"
SECRET_KEY = "6MPjbdQyG6PmWP1niRAAGPFM3HQw2SvAWMGWL3r5Q3FM"
NEWS_URL = "https://data.alpaca.markets/v1beta1/news"
HEADERS = {
    "Apca-Api-Key-Id": API_KEY,
    "Apca-Api-Secret-Key": SECRET_KEY,
    "accept": "application/json"
}

# 2. Fetching Parameters
symbol = "AAPL"
LIMIT = 500  # Target: Fetch 500 articles
START_DATE = "2026-01-01T00:00:00Z"
END_DATE = "2026-01-31T23:59:59Z"

all_news = []
page_token = None

print(f"📡 Fetching January news for {symbol}...")

while len(all_news) < LIMIT:
    params = {
        "symbols": symbol,
        "start": START_DATE,
        "end": END_DATE,
        "limit": 50,
        "page_token": page_token
    }

    try:
        response = requests.get(NEWS_URL, headers=HEADERS, params=params)
        if response.status_code == 200:
            data = response.json()
            articles = data.get('news', [])

            if not articles:
                break

            for art in articles:
                if len(all_news) < LIMIT:
                    all_news.append({
                        "Ticker": symbol,
                        "Date": art.get('created_at'),
                        "Headline": art.get('headline'),
                        "Source": art.get('source')
                    })

            print(f"   Progress: {len(all_news)}/{LIMIT} articles fetched", end='\r')

            # Pagination handling
            page_token = data.get('next_page_token')
            if not page_token:
                break
            time.sleep(0.2)  # Rate limiting protection
        else:
            print(f"\n⚠️ Request Failed. Status Code: {response.status_code}")
            break
    except Exception as e:
        print(f"\n❌ Error encountered: {e}")
        break

# 3. Data Persistence
if all_news:
    df_aapl = pd.DataFrame(all_news)
    # Save the raw data for January 2026
    df_aapl.to_csv("aapl_jan_2026.csv", index=False)
    print(f"\n\n🎉 Success! AAPL news for January has been saved to 'aapl_jan_2026.csv'")
else:
    print("\n💀 No data found. Please verify your API Key permissions or date range.")

# ⬇️ Calculate the sentiment score

import pandas as pd
import requests
import time
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# 1. API Configuration
# Credentials for Alpaca Market Data API
API_KEY = "PKVESCM6H235I3XWBT25AYP7JC"
SECRET_KEY = "6MPjbdQyG6PmWP1niRAAGPFM3HQw2SvAWMGWL3r5Q3FM"
NEWS_URL = "https://data.alpaca.markets/v1beta1/news"
HEADERS = {
    "Apca-Api-Key-Id": API_KEY,
    "Apca-Api-Secret-Key": SECRET_KEY,
    "accept": "application/json"
}

# 2. Data Acquisition Logic
symbol = "AAPL"
START_DATE = "2026-01-01T00:00:00Z"
END_DATE = "2026-01-31T23:59:59Z"
FETCH_LIMIT = 500
all_news = []
page_token = None

print(f"📡 Fetching January news data for {symbol}...")

while len(all_news) < FETCH_LIMIT:
    params = {
        "symbols": symbol,
        "start": START_DATE,
        "end": END_DATE,
        "limit": 50,
        "page_token": page_token
    }

    response = requests.get(NEWS_URL, headers=HEADERS, params=params)
    if response.status_code != 200:
        break

    data = response.json()
    articles = data.get('news', [])
    if not articles:
        break

    for art in articles:
        if len(all_news) < FETCH_LIMIT:
            all_news.append({
                "Date": art.get('created_at'),
                "Headline": art.get('headline')
            })

    # Handle API pagination
    page_token = data.get('next_page_token')
    print(f"   Progress: {len(all_news)}/{FETCH_LIMIT} articles collected", end='\r')

    if not page_token:
        break
    time.sleep(0.2)  # Defensive delay to prevent rate limiting

# 3. Sentiment Analysis (VADER Engine)
# Initialize the rule-based sentiment analyzer
nltk.download('vader_lexicon', quiet=True)
sia = SentimentIntensityAnalyzer()

df = pd.DataFrame(all_news)

# Calculate 'compound' scores (range: -1 to 1) for semantic feature extraction
df['sentiment_score'] = df['Headline'].apply(lambda x: sia.polarity_scores(str(x))['compound'])

# 4. Temporal Feature Engineering
df['Date'] = pd.to_datetime(df['Date'])
# Create a unique Year_Week identifier to handle multi-year datasets
df['Year_Week'] = df['Date'].dt.isocalendar().year.astype(str) + "_" + \
                  df['Date'].dt.isocalendar().week.astype(str).str.zfill(2)

# Calculate the arithmetic mean of sentiment scores per week (Noise Reduction)
aapl_weekly_sentiment = df.groupby('Year_Week')['sentiment_score'].mean().reset_index()

print("\n\n✅ Step 1 Complete: Weekly Sentiment Time-Series Generated.")
print(aapl_weekly_sentiment)

# Get the real return of T+1 week based on the news time

from alpaca_trade_api.rest import REST
import pandas as pd

# 1. Initialize Alpaca REST API
# Using the Paper Trading endpoint for simulated backtesting
api = REST(API_KEY, SECRET_KEY, base_url='https://paper-api.alpaca.markets')

# 2. Historical Market Data Acquisition (Weekly Candles)
# Fetching an extended range to ensure T+1 alignment (Jan to mid-Feb 2026)
bars = api.get_bars("AAPL", '1Week', start="2026-01-01", end="2026-02-15").df
bars = bars.reset_index()

# 3. Calculate Target Variable: Next Week's Percentage Return (T+1)
# .pct_change() calculates the return between consecutive weeks
# .shift(-1) aligns next week's return with the current week's sentiment signal
bars['next_week_ret'] = bars['close'].pct_change().shift(-1)

# 4. Feature Synchronization
# Extracting Year_Week to ensure precise merging with the sentiment dataset
bars['Year_Week'] = bars['timestamp'].dt.isocalendar().year.astype(str) + "_" + \
                    bars['timestamp'].dt.isocalendar().week.astype(str).str.zfill(2)

# Drop the final row as it will contain a NaN for the shifted 'next_week_ret'
df_prices = bars[['Year_Week', 'next_week_ret']].dropna()

print("\n✅ Step 2 Complete: AAPL Historical Returns Prepared.")
print(df_prices)

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# --- 1. Performance Reconciliation (Merging Sentiment Signals with Market Returns) ---
# Ensure 'aapl_weekly_sentiment' and 'df_prices' have been generated in previous cells
final_check = pd.merge(aapl_weekly_sentiment, df_prices, on='Year_Week').sort_values('Year_Week')

# 2. Predictive Accuracy Logic (Hit Rate Calculation)
# Definition: A prediction is "Correct" if the sentiment direction aligns with the subsequent return direction
final_check['is_correct'] = ((final_check['sentiment_score'] > 0) & (final_check['next_week_ret'] > 0)) | \
                            ((final_check['sentiment_score'] < 0) & (final_check['next_week_ret'] < 0))

# Calculate the mean of boolean values to get the percentage of correct predictions
hit_rate = final_check['is_correct'].mean()

print(f"\n🎯 --- AAPL January 2026 Predictive Performance Report ---")
print(f"Prediction Accuracy (Hit Rate): {hit_rate:.2%}")

# Display the alignment for clarity: News Signal (Week T) vs Price Target (Week T+1)
print(final_check[['Year_Week', 'sentiment_score', 'next_week_ret', 'is_correct']])


# --- 3. Dual-Axis Time-Series Visualization ---
# Using a dual-axis plot to compare two different scales (Score vs. Percentage)

fig, ax1 = plt.subplots(figsize=(12, 6))

# Instantiate a second axes that shares the same x-axis
ax2 = ax1.twinx()

# Plot Primary Axis (Left): Weekly Sentiment Score (The Predictor)
line1, = ax1.plot(final_check['Year_Week'], final_check['sentiment_score'],
                  color='#1f77b4', linewidth=2.5, marker='s', markersize=8,
                  label='Sentiment Score (Week T)')

# Plot Secondary Axis (Right): Actual Returns (The Target)
# Note: These values are shifted T+1 returns plotted against the signal week
line2, = ax2.plot(final_check['Year_Week'], final_check['next_week_ret'],
                  color='#d62728', linewidth=2.5, marker='o', markersize=8, linestyle='--',
                  label='Stock Return (Week T+1)')


# --- 4. Chart Customization & Aesthetics ---

# Axis Labels and Styling
ax1.set_xlabel('Time Window (Year_Week)', fontsize=12, fontweight='bold')
ax1.set_ylabel('Sentiment Polarity Score', color='#1f77b4', fontsize=12, fontweight='bold')
ax2.set_ylabel('Forward Asset Return (%)', color='#d62728', fontsize=12, fontweight='bold')

# Tick Formatting
ax1.tick_params(axis='y', labelcolor='#1f77b4')
ax2.tick_params(axis='y', labelcolor='#d62728')

# Display returns as a percentage for better financial readability
ax2.yaxis.set_major_formatter(mticker.PercentFormatter(1.0, decimals=1))

# Grid and Baseline (Neutral Sentiment Line)
ax1.grid(True, linestyle='-', alpha=0.2)
ax1.axhline(0, color='black', linewidth=1, linestyle='-', alpha=0.5)

# Legend Configuration (Merging labels from both axes)
lines = [line1, line2]
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc='upper left', fontsize=10, frameon=True, shadow=True)

# Chart Title
plt.title('Lead-Lag Analysis: AAPL Sentiment (Week T) vs. Stock Return (Week T+1)',
          fontsize=14, fontweight='bold', pad=20)

# Rotated x-ticks for better readability of week strings
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""The result of one-month trend above showed 50% accuracy, likely due to a limited time horizon.

To improve model robustness, the study period has been expanded to a **6-month** window (2025.09.01 - 2026.02.28).



"""

import pandas as pd
import requests
import time
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# 1. API Configuration
# Credentials for Alpaca Market Data API
API_KEY = "PKVESCM6H235I3XWBT25AYP7JC"
SECRET_KEY = "6MPjbdQyG6PmWP1niRAAGPFM3HQw2SvAWMGWL3r5Q3FM"
NEWS_URL = "https://data.alpaca.markets/v1beta1/news"
HEADERS = {
    "Apca-Api-Key-Id": API_KEY,
    "Apca-Api-Secret-Key": SECRET_KEY,
    "accept": "application/json"
}

# 2. 6-Month Historical Data Acquisition (2025.09.01 - 2026.02.28)
# Expanding the timeframe to increase statistical significance and reduce noise
symbol = "AAPL"
LIMIT = 2000  # Increased limit for a robust 6-month sample
START_DATE = "2025-09-01T00:00:00Z"
END_DATE = "2026-02-28T23:59:59Z"
all_news = []
page_token = None

print(f"📡 Fetching 6 months of historical news data for {symbol}...")

while len(all_news) < LIMIT:
    params = {
        "symbols": symbol,
        "start": START_DATE,
        "end": END_DATE,
        "limit": 50,
        "page_token": page_token
    }

    try:
        response = requests.get(NEWS_URL, headers=HEADERS, params=params)
        if response.status_code != 200:
            break

        data = response.json()
        articles = data.get('news', [])
        if not articles:
            break

        for art in articles:
            if len(all_news) < LIMIT:
                all_news.append({
                    "Date": art.get('created_at'),
                    "Headline": art.get('headline')
                })

        page_token = data.get('next_page_token')
        print(f"   Progress: {len(all_news)}/{LIMIT} articles collected", end='\r')

        if not page_token:
            break
        time.sleep(0.1)  # Throttling to prevent API rate limiting
    except Exception as e:
        print(f"\n❌ Error: {e}")
        break

# 3. Sentiment Analysis & Weekly Aggregation
# Using VADER for rule-based semantic feature extraction
nltk.download('vader_lexicon', quiet=True)
sia = SentimentIntensityAnalyzer()

# Data Cleaning: Remove duplicate headlines to prevent sentiment bias
df = pd.DataFrame(all_news).drop_duplicates(subset=['Headline'])

# Sentiment Scoring: Calculate the 'compound' polarity score (-1 to 1)
df['sentiment_score'] = df['Headline'].apply(lambda x: sia.polarity_scores(str(x))['compound'])
df['Date'] = pd.to_datetime(df['Date'])

# ✨ CRITICAL: Temporal Feature Engineering
# Create 'Year_Week' identifier (e.g., 2025_40) to prevent cross-year overlaps
df['Year_Week'] = df['Date'].dt.isocalendar().year.astype(str) + "_" + \
                  df['Date'].dt.isocalendar().week.astype(str).str.zfill(2)

# Calculate the mean sentiment per week (Smoothing daily volatility)
weekly_sentiment = df.groupby('Year_Week')['sentiment_score'].mean().reset_index()

print(f"\n\n✅ Step 1 Complete: Processed {len(df)} unique headlines.")
print(f"✅ Generated {len(weekly_sentiment)} weekly sentiment signals.")

from alpaca_trade_api.rest import REST
import pandas as pd

# 1. Initialize Alpaca REST API
# Using the Paper Trading endpoint for data consistency
api = REST(API_KEY, SECRET_KEY, base_url='https://paper-api.alpaca.markets')

# 2. Historical Market Data Acquisition (Weekly Candles)
# Fetching an extended range through March to ensure T+1 alignment for the Feb data
bars = api.get_bars("AAPL", "1Week", start="2025-09-01", end="2026-03-07").df
bars = bars.reset_index()

# 3. Core Predictive Logic: Target Variable Synchronization
# We calculate the weekly percentage change and apply a negative shift (-1).
# This aligns 'Next Week's Return' with 'Current Week's Sentiment Signal'.
bars['next_week_ret'] = bars['close'].pct_change().shift(-1)

# 4. Temporal Feature Engineering: ISO Year_Week Formatting
# Consistent formatting (e.g., 2025_45) to ensure a seamless merge with sentiment data
bars['Year_Week'] = bars['timestamp'].dt.isocalendar().year.astype(str) + "_" + \
                    bars['timestamp'].dt.isocalendar().week.astype(str).str.zfill(2)

# 5. Data Cleaning: Drop the final row (NaN due to the shift)
df_prices = bars[['Year_Week', 'next_week_ret']].dropna()

print("\n✅ Step 2 Complete: 6-Month AAPL Historical Returns Prepared.")
print(f"✅ Synchronized {len(df_prices)} weekly return data points.")

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# --- 1. Dataset Consolidation (Merging Sentiment Signals with Market Returns) ---
# Merging the 6-month sentiment time-series with the T+1 price returns
final_check = pd.merge(weekly_sentiment, df_prices, on='Year_Week').sort_values('Year_Week')

# --- 2. Performance Metrics Calculation ---
# Hit Rate: A prediction is "Correct" if the sentiment polarity matches the return direction
final_check['is_correct'] = ((final_check['sentiment_score'] > 0) & (final_check['next_week_ret'] > 0)) | \
                            ((final_check['sentiment_score'] < 0) & (final_check['next_week_ret'] < 0))

hit_rate = final_check['is_correct'].mean()
# Correlation: Measures the linear relationship between Sentiment(T) and Return(T+1)
correlation = final_check['sentiment_score'].corr(final_check['next_week_ret'])

print(f"\n🎯 --- AAPL 6-Month Predictive Blind Test Report ---")
print(f"Total Observation Weeks: {len(final_check)}")
print(f"Prediction Accuracy (Hit Rate): {hit_rate:.2%}")
print(f"Sentiment-Return Correlation (Lead-Lag): {correlation:.4f}")


# --- 3. Dual-Axis Time-Series Visualization ---
# Plotting two different scales (Score vs. Percentage) to identify trends
fig, ax1 = plt.subplots(figsize=(14, 6))
ax2 = ax1.twinx()

# Primary Axis (Left): Sentiment Score (The Leading Indicator)
ax1.plot(final_check['Year_Week'], final_check['sentiment_score'],
         color='#1f77b4', marker='s', linewidth=2, label='Sentiment Score (Week T)')

# Secondary Axis (Right): Actual Asset Returns (The Lagging Target)
ax2.plot(final_check['Year_Week'], final_check['next_week_ret'],
         color='#d62728', marker='o', linestyle='--', linewidth=2, label='Stock Return (Week T+1)')

# --- 4. Chart Aesthetics & Formatting ---
ax1.set_ylabel('Sentiment Polarity (VADER)', color='#1f77b4', fontsize=12, fontweight='bold')
ax2.set_ylabel('Forward Weekly Return (%)', color='#d62728', fontsize=12, fontweight='bold')

# Formatting the Y-axis to show percentage values
ax2.yaxis.set_major_formatter(mticker.PercentFormatter(1.0))

# Adding a chart title that highlights the Hit Rate
plt.title(f'AAPL: 6-Month Predictive Backtest (Hit Rate: {hit_rate:.2%})',
          fontsize=14, fontweight='bold', pad=20)

# Improving X-axis readability for Year_Week strings
ax1.tick_params(axis='x', rotation=45)

# Adding a zero-baseline for sentiment neutrality
ax1.axhline(0, color='black', linewidth=1, alpha=0.3)

# Merging legends from both axes
ax1.legend(loc='upper left', frameon=True)
ax2.legend(loc='upper right', frameon=True)

plt.tight_layout()
plt.show()

"""❌ The hit rate is low at 42.31%.

To capture more nuanced financial context, we are upgrading the sentiment engine to **FinBERT** for better signal extraction.
"""

# Install the necessary Deep Learning libraries
!pip install transformers torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import pandas as pd

# --- 1. Model & Tokenizer Initialization ---
# We are utilizing "ProsusAI/finbert", a pre-trained NLP model
# specifically fine-tuned on financial corpora (Financial PhraseBank).
model_name = "ProsusAI/finbert"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# --- 2. Hardware Acceleration (GPU Check) ---
# Deep Learning models (Transformers) are computationally expensive.
# We check for CUDA availability to leverage NVIDIA T4 GPU acceleration in Colab.
device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

print(f"🚀 FinBERT Model successfully loaded on: {device.upper()}")

# Extract the news of AAPL for 6-month (2025.9.1- 2026.2.28)

import pandas as pd
import requests
import time

# 1. API Configuration
# Ensure your API_KEY and SECRET_KEY remain active for the Alpaca Market Data API
API_KEY = "PKVESCM6H235I3XWBT25AYP7JC"
SECRET_KEY = "6MPjbdQyG6PmWP1niRAAGPFM3HQw2SvAWMGWL3r5Q3FM"
NEWS_URL = "https://data.alpaca.markets/v1beta1/news"
HEADERS = {
    "Apca-Api-Key-Id": API_KEY,
    "Apca-Api-Secret-Key": SECRET_KEY,
    "accept": "application/json"
}

# 2. 6-Month Timeframe Configuration (Longitudinal Study)
# Period: September 2025 to February 2026
symbol = "AAPL"
LIMIT = 2000  # Increased limit to provide a statistically significant sample size
START_DATE = "2025-09-01T00:00:00Z"
END_DATE = "2026-02-28T23:59:59Z"

all_news = []
page_token = None

print(f"📡 Initiating Data Acquisition for {symbol} (6-Month Period: 2025.09 - 2026.02)...")

while len(all_news) < LIMIT:
    params = {
        "symbols": symbol,
        "start": START_DATE,
        "end": END_DATE,
        "limit": 50,
        "page_token": page_token
    }

    try:
        response = requests.get(NEWS_URL, headers=HEADERS, params=params)
        if response.status_code != 200:
            print(f"\n⚠️ Connection error: Status Code {response.status_code}")
            break

        data = response.json()
        articles = data.get('news', [])

        if not articles:
            break

        for art in articles:
            if len(all_news) < LIMIT:
                all_news.append({
                    "Date": art.get('created_at'),
                    "Headline": art.get('headline')
                })

        # Handle API Pagination
        page_token = data.get('next_page_token')
        print(f"   Progress: {len(all_news)}/{LIMIT} articles collected", end='\r')

        if not page_token:
            break
        time.sleep(0.1)  # Defensive throttling to prevent API rate limiting

    except Exception as e:
        print(f"\n❌ Unexpected error occurred: {e}")
        break

# 3. Data Persistence & Deduplication
# Removing identical headlines to prevent sentiment bias and signal skewing
df_6m = pd.DataFrame(all_news).drop_duplicates(subset=['Headline'])
df_6m.to_csv("aapl_6_months.csv", index=False)

print(f"\n\n✅ Success! Dataset generated: 'aapl_6_months.csv'")
print(f"✅ Final count: {len(df_6m)} unique records successfully saved.")

# Calculate the Weekly Sentiment Score

from tqdm.auto import tqdm
import torch
import pandas as pd

# 1. Initialize Progress Monitoring
# tqdm.pandas() allows us to visualize the processing speed of our dataframe
tqdm.pandas()

print("🧠 FinBERT Deep Scoring Engine Activated (Hardware Acceleration: GPU)...")

# 2. Data Loading
# Loading the 6-month longitudinal dataset (AAPL)
df = pd.read_csv("aapl_6_months.csv")

# 3. Sentiment Inference Logic
def get_finbert_sentiment(text, index):
    """
    Performs NLP inference using FinBERT.
    Includes periodic logging to monitor model 'thinking' process.
    """
    # Standard Tokenization and Inference
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=512).to(device)
    with torch.no_grad():
        outputs = model(**inputs)

    # Apply Softmax to convert raw logits into probability distributions
    probs = torch.nn.functional.softmax(outputs.logits, dim=-1)

    # Calculate Score: Positive Probability - Negative Probability
    # Index 0: Positive, Index 1: Negative, Index 2: Neutral
    score = probs[0][0].item() - probs[0][1].item()

    # Real-time Sampling: Print every 100th record to verify inference quality
    if index % 100 == 0:
        label = "BULLISH" if score > 0.2 else ("BEARISH" if score < -0.2 else "NEUTRAL")
        print(f"📍 Sample [{index}/{len(df)}] | Score: {score:.2f} ({label}) | Text: {text[:60]}...")

    return score

# 4. Execute Inference Loop
print("\n🚀 Analyzing headlines via Deep Learning Transformer...")
# We use a list comprehension with enumerate to track index for our logging logic
df['sentiment_score'] = [get_finbert_sentiment(row['Headline'], i) for i, row in enumerate(tqdm(df.to_dict('records')))]

# 5. Temporal Feature Engineering & Aggregation
df['Date'] = pd.to_datetime(df['Date'])
# ISO Year_Week formatting for seamless cross-year time-series alignment
df['Year_Week'] = df['Date'].dt.isocalendar().year.astype(str) + "_" + \
                  df['Date'].dt.isocalendar().week.astype(str).str.zfill(2)

# Arithmetic mean aggregation to generate weekly sentiment signals (Noise Reduction)
weekly_sentiment_finbert = df.groupby('Year_Week')['sentiment_score'].mean().reset_index()

print("\n✅ Inference Task Completed Successfully!")
print("📊 Weekly Sentiment Summary (FinBERT Engine):")
print(weekly_sentiment_finbert.head())

# --- STEP 2: Market Data & Alignment ---

# Fetch 1Week bars for AAPL (Extended range for T+1)
bars = api.get_bars("AAPL", '1Week', start="2025-09-01", end="2026-03-07").df
bars = bars.reset_index()

# Align 'Next Week Return' with 'Current Signal' (T+1)
bars['next_week_ret'] = bars['close'].pct_change().shift(-1)

# Format Year_Week for merging
bars['Year_Week'] = bars['timestamp'].dt.isocalendar().year.astype(str) + "_" + \
                    bars['timestamp'].dt.isocalendar().week.astype(str).str.zfill(2)

df_prices = bars[['Year_Week', 'next_week_ret']].dropna()
print("✅ Step 2 Complete: Market returns synchronized.")

import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

# --- 1. Signal-Return Integration ---
# Merging FinBERT weekly sentiment scores with realized T+1 market returns
final_check = pd.merge(weekly_sentiment_finbert, df_prices, on='Year_Week').sort_values('Year_Week')

# --- 2. Predictive Accuracy & Signal Filtering ---
# Noise Filtering: Only consider signals valid if the absolute score > 0.02
# This ensures we only trade on high-confidence sentiment trends.
final_check['is_correct'] = ((final_check['sentiment_score'] > 0.02) & (final_check['next_week_ret'] > 0)) | \
                            ((final_check['sentiment_score'] < -0.02) & (final_check['next_week_ret'] < 0))

# Performance Metrics: Calculate hit rate only for "Active Signal" weeks
active_signals = final_check[final_check['sentiment_score'].abs() > 0.02]
hit_rate = active_signals['is_correct'].mean()
correlation = final_check['sentiment_score'].corr(final_check['next_week_ret'])

print(f"\n🎯 --- AAPL FinBERT 6-Month Predictive Backtest Report ---")
print(f"Total Observation Weeks: {len(final_check)}")
print(f"Active Signal Weeks (Filtered): {len(active_signals)}")
print(f"Prediction Accuracy (Hit Rate): {hit_rate:.2%}")
print(f"FinBERT-Return Correlation (Lead-Lag): {correlation:.4f}")


# --- 3. Dual-Axis Temporal Visualization ---
# Comparing the NLP Signal (Week T) against the Market Reality (Week T+1)
fig, ax1 = plt.subplots(figsize=(15, 7))
ax2 = ax1.twinx()

# Plotting Primary Axis (Left): FinBERT Sentiment (The Leading Predictor)
ax1.plot(final_check['Year_Week'], final_check['sentiment_score'],
         color='#0052cc', marker='s', linewidth=2.5, label='FinBERT Sentiment (Week T)')

# Plotting Secondary Axis (Right): Realized Returns (The Lagging Target)
ax2.plot(final_check['Year_Week'], final_check['next_week_ret'],
         color='#ff4d4d', marker='o', linestyle='--', linewidth=2.5, label='Next Week Return (%)')

# --- 4. Chart Formatting & Aesthetics ---
ax1.set_ylabel('FinBERT Sentiment Score', color='#0052cc', fontsize=12, fontweight='bold')
ax2.set_ylabel('AAPL Realized Return (Week T+1)', color='#ff4d4d', fontsize=12, fontweight='bold')

# Displaying returns as percentage values for financial clarity
ax2.yaxis.set_major_formatter(mticker.PercentFormatter(1.0))

# Adding a comprehensive title including the final performance metric
plt.title(f'AAPL: FinBERT Predictive Power Analysis (Hit Rate: {hit_rate:.2%})',
          fontsize=14, fontweight='bold', pad=20)

# Improving X-axis readability for Year_Week identifiers
ax1.tick_params(axis='x', rotation=45)

# Adding a zero-baseline for sentiment neutrality
ax1.axhline(0, color='black', linewidth=1, alpha=0.3)

# Consolidating legends from both axes
ax1.legend(loc='upper left', frameon=True, shadow=True)
ax2.legend(loc='upper right', frameon=True, shadow=True)

plt.tight_layout()
plt.show()